### ISSUE TITLE
Problem in the notebook steps sequence

### ISSUE THREAD

**Issue by tal2k4xj** [IBM/monitor-wml-model-with-watson-openscale#28]
At the "Enable quality monitoring" step there is a call to enable quality monitoring with threshold and minrecords, the problem is that it gives error when you try to run it 
![Screenshot_3](https://user-images.githubusercontent.com/11144416/54519922-3a03c080-4970-11e9-8b47-949aaab588a6.png)

I found out that you need to run the "Insert historical payloads" section before that to make it work like in the pictures below, to be more accurate what need to be done is the store payload logging function : ```subscription.payload_logging.store(records=recordsList)```
![Screenshot_1](https://user-images.githubusercontent.com/11144416/54520105-923ac280-4970-11e9-8d3c-d70924ba3e8d.png)

![Screenshot_2](https://user-images.githubusercontent.com/11144416/54520113-9b2b9400-4970-11e9-9b7d-3d752c4b4efa.png)

**Comment by scottdangelo** [comment]
This should be fixed. Please reopen, or open a new issue, if you still have problems.

**Comment by scottdangelo** [comment]
Reopening as Tal is still seeing this issue.

**Comment by scottdangelo** [comment]
One possible cause is that only WML in Dallas sends events about scoring requests to the message hub,
and OpenScale reads those events to populate the payload logging table.
Otherwise, the user will have to log them manually  on his/her own.
