### ISSUE TITLE
Having issues running the notebook in my environment

### ISSUE THREAD

**Issue by kavithadurgi** [IBM/monitor-wml-model-with-watson-openscale#30]
I have an instance of Spark created in my cloud and use it as runtime for this notebook. I get the following error and am not able to resolve it. I would like to demo OpenScale, can someone please take a look at the error and fix it? I reached out to Lukasz Cmielowski and he asked me to open this issue. Thank you. 

Here is the code I get the error in:
from pyspark.ml.classification import RandomForestClassifier
classifier = RandomForestClassifier(featuresCol="features")

pipeline = Pipeline(stages=[si_CheckingStatus, si_CreditHistory, si_EmploymentDuration, si_ExistingSavings, si_ForeignWorker, si_Housing, si_InstallmentPlans, si_Job, si_LoanPurpose, si_OthersOnLoan, si_OwnsProperty, si_Sex, si_Telephone, si_Label, va_features, classifier, label_converter])
model = pipeline.fit(train_data)

Here is the error:
Py4JJavaError                             Traceback (most recent call last)
/usr/local/src/spark21master/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:

/usr/local/src/spark21master/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:

Py4JJavaError: An error occurred while calling o163.transform.
: java.lang.IllegalArgumentException: Data type StringType is not supported.
	at org.apache.spark.ml.feature.VectorAssembler$$anonfun$transformSchema$1.apply(VectorAssembler.scala:121)
	at org.apache.spark.ml.feature.VectorAssembler$$anonfun$transformSchema$1.apply(VectorAssembler.scala:117)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.spark.ml.feature.VectorAssembler.transformSchema(VectorAssembler.scala:117)
	at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:74)
	at org.apache.spark.ml.feature.VectorAssembler.transform(VectorAssembler.scala:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:812)

During handling of the above exception, another exception occurred:

IllegalArgumentException                  Traceback (most recent call last)
<ipython-input-21-c330ccf92bdc> in <module>()
      3 
      4 pipeline = Pipeline(stages=[si_CheckingStatus, si_CreditHistory, si_EmploymentDuration, si_ExistingSavings, si_ForeignWorker, si_Housing, si_InstallmentPlans, si_Job, si_LoanPurpose, si_OthersOnLoan,                               si_OwnsProperty, si_Sex, si_Telephone, si_Label, va_features, classifier, label_converter])
----> 5 model = pipeline.fit(train_data)

/usr/local/src/spark21master/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
     62                 return self.copy(params)._fit(dataset)
     63             else:
---> 64                 return self._fit(dataset)
     65         else:
     66             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/usr/local/src/spark21master/spark/python/pyspark/ml/pipeline.py in _fit(self, dataset)
    104                 if isinstance(stage, Transformer):
    105                     transformers.append(stage)
--> 106                     dataset = stage.transform(dataset)
    107                 else:  # must be an Estimator
    108                     model = stage.fit(dataset)

/usr/local/src/spark21master/spark/python/pyspark/ml/base.py in transform(self, dataset, params)
    103                 return self.copy(params)._transform(dataset)
    104             else:
--> 105                 return self._transform(dataset)
    106         else:
    107             raise ValueError("Params must be a param map but got %s." % type(params))

/usr/local/src/spark21master/spark/python/pyspark/ml/wrapper.py in _transform(self, dataset)
    250     def _transform(self, dataset):
    251         self._transfer_params_to_java()
--> 252         return DataFrame(self._java_obj.transform(dataset._jdf), dataset.sql_ctx)
    253 
    254 

/usr/local/src/spark21master/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/local/src/spark21master/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     77                 raise QueryExecutionException(s.split(': ', 1)[1], stackTrace)
     78             if s.startswith('java.lang.IllegalArgumentException: '):
---> 79                 raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
     80             raise
     81     return deco

IllegalArgumentException: 'Data type StringType is not supported.'

**Comment by scottdangelo** [comment]
I have tested this in Watson Studio using Python 3.5 and Spark 2.1
What environment are you using?
Is it possible for you to test with the same environment that I am using?

**Comment by kavithadurgi** [comment]
Hi Scott, I am using Python 3.5 and Spark 2.1, I have also tested this with Python 2 and Spark 2.1 and I get the same error, I can add you to my WS, if you want to debug in my environment. Let me know.

**Comment by scottdangelo** [comment]
Yes, please add me and I can have a look. scott.dangelo@ibm.com

**Comment by kavithadurgi** [comment]
Hi Scott, added you as an admin. Thank you.

**Comment by scottdangelo** [comment]
You are running a different notebook than the one in this repository. I recommend that you use the notebook as is, since that is what I have tested on. The notebook in the repo has been tested and it works.

**Comment by kavithadurgi** [comment]
Hi Scott, my notebook was picked up from this repository, I had to change a few things to make it run in my environment, however I started again with a new notebook. Some instructions are not clear to me. I am using a DB2 Warehouse on cloud and put that in the DB_CREDENTIALS. 

1) I should add my DB2 credentials to DB_CREDENTIALS? What do you mean by configured OpenScale before? I don't have a paid IBM Cloud, so I need to use DB2.
**If you have previously configured OpenScale, it will use your existing datamart, and not interfere with any models you are currently monitoring. Do not update the cell below.**

2) In my previous notebook, I used a PostgreSQL from my colleague, it was not provisioned in my account. Does that affect the runtime that your notebook runs in? I was not able to get it to work.

**Comment by kavithadurgi** [comment]
Hi Scott,

I ran 2 different notebooks, one using the internal Postgre DB that is part of the OpenScale (TestNotebookDD), other with DB2 (OpenScaleDD). Both fail to work. Please find me on ST or Slack, I'd like to debug with you. I wanted to demo OpenScale for my team and want to have this working. Thanks.

Both fail when I am setting up Datamart. When I use DB2, here is the error:
Setting up external datamart
Setup failed, trying Db2 setup
---------------------------------------------------------------------------
ApiRequestFailure                         Traceback (most recent call last)
<ipython-input-72-24013b62ab78> in <module>()
      4 try:
----> 5     data_mart_details = ai_client.data_mart.get_details()
      6     if 'internal_database' in data_mart_details and data_mart_details['internal_database']:

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/data_mart.py in get_details(self)
    201 
--> 202         result = handle_response(200, "getting data mart details", response, True)
    203 

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/utils/utils.py in handle_response(expected_status_code, operationName, response, json_response)
    136     else:
--> 137         raise ApiRequestFailure(u'Failure during {}.'.format(operationName), response)
    138 

ApiRequestFailure: Failure during getting data mart details. (GET https://api.aiopenscale.cloud.ibm.com/v1/data_marts/71e2a72a-f984-4a1f-b07f-89130f8097ad)
Status code: 404, body: {"trace":"NTEzMTAzNGUtZDk4Mi00Y2I5LThmNjUtOWI4NGFmMWVmN2Ix","errors":[{"code":"AIQCS0005W","message":"Data Mart with given id could not be found"}]}

During handling of the above exception, another exception occurred:

ApiRequestFailure                         Traceback (most recent call last)
<ipython-input-72-24013b62ab78> in <module>()
     24         try:
---> 25             ai_client.data_mart.setup(db_credentials=DB_CREDENTIALS)
     26         except:

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/data_mart.py in setup(self, db_credentials, schema, internal_db)
    162         try:
--> 163             handle_response(200, "setup of data mart", response, False)
    164         except ApiRequestWarning:

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/utils/utils.py in handle_response(expected_status_code, operationName, response, json_response)
    136     else:
--> 137         raise ApiRequestFailure(u'Failure during {}.'.format(operationName), response)
    138 

ApiRequestFailure: Failure during setup of data mart. (PUT https://api.aiopenscale.cloud.ibm.com/v1/data_marts/71e2a72a-f984-4a1f-b07f-89130f8097ad)
Status code: 500, body: {"trace":"OTk0YmIxZjUtOGM2MC00YTQ1LTg3NTctNDIxMDdhMDZhMTYz","errors":[{"code":"AIQCS0002E","message":"Action `Create Measurement Tables` has failed with status code 400"},{"code":"AIQDT0006E","message":"Failed to create database object - associated message: \"DASH101147\" does not have the privilege to perform operation \"CREATE SCHEMA\".. SQLCODE=-552, SQLSTATE=42502, DRIVER=4.21.29","parameters":["\"DASH101147\" does not have the privilege to perform operation \"CREATE SCHEMA\".. SQLCODE=-552, SQLSTATE=42502, DRIVER=4.21.29"]}]}

During handling of the above exception, another exception occurred:

ApiRequestFailure                         Traceback (most recent call last)
<ipython-input-72-24013b62ab78> in <module>()
     26         except:
     27             print('Setup failed, trying Db2 setup')
---> 28             ai_client.data_mart.setup(db_credentials=DB_CREDENTIALS, schema=DB_CREDENTIALS['username'])

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/data_mart.py in setup(self, db_credentials, schema, internal_db)
    161 
    162         try:
--> 163             handle_response(200, "setup of data mart", response, False)
    164         except ApiRequestWarning:
    165             ApiRequestWarning.print_msg(error_msg=u'Warning during {}.'.format('setup of data mart'), response=response)

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/utils/utils.py in handle_response(expected_status_code, operationName, response, json_response)
    135         raise ApiRequestWarning(u'Warning during {}.'.format(operationName), response)
    136     else:
--> 137         raise ApiRequestFailure(u'Failure during {}.'.format(operationName), response)
    138 
    139 

ApiRequestFailure: Failure during setup of data mart. (PUT https://api.aiopenscale.cloud.ibm.com/v1/data_marts/71e2a72a-f984-4a1f-b07f-89130f8097ad)
Status code: 500, body: {"trace":"OGIyMTI2NDctN2VlZS00NjllLTkzOTktMGY2MWM0MzVmZDMy","errors":[{"code":"AIQCS0002E","message":"Action `Create Measurement Tables` has failed with status code 400"},{"code":"AIQDT0006E","message":"Failed to create database object - associated message: A table space could not be found with a page size of at least \"4096\" that authorization ID \"DASH101147\" is authorized to use.. SQLCODE=-286, SQLSTATE=42727, DRIVER=4.21.29","parameters":["A table space could not be found with a page size of at least \"4096\" that authorization ID \"DASH101147\" is authorized to use.. SQLCODE=-286, SQLSTATE=42727, DRIVER=4.21.29"]}]}

======================
When I use the internal postgre, here is the error:

Setting up external datamart
Setup failed, trying Db2 setup
---------------------------------------------------------------------------
ApiRequestFailure                         Traceback (most recent call last)
<ipython-input-28-31615d0e23f2> in <module>()
      1 try:
----> 2     data_mart_details = ai_client.data_mart.get_details()
      3     if 'internal_database' in data_mart_details and data_mart_details['internal_database']:

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/data_mart.py in get_details(self)
    201 
--> 202         result = handle_response(200, "getting data mart details", response, True)
    203 

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/utils/utils.py in handle_response(expected_status_code, operationName, response, json_response)
    136     else:
--> 137         raise ApiRequestFailure(u'Failure during {}.'.format(operationName), response)
    138 

ApiRequestFailure: Failure during getting data mart details. (GET https://api.aiopenscale.cloud.ibm.com/v1/data_marts/71e2a72a-f984-4a1f-b07f-89130f8097ad)
Status code: 404, body: {"trace":"NzY0NWE4OWEtNzE2NC00Yjk3LThmNGQtZDg4YWIxNzkyYTc3","errors":[{"code":"AIQCS0005W","message":"Data Mart with given id could not be found"}]}

During handling of the above exception, another exception occurred:

ClientError                               Traceback (most recent call last)
<ipython-input-28-31615d0e23f2> in <module>()
     21         try:
---> 22             ai_client.data_mart.setup(db_credentials=DB_CREDENTIALS)
     23         except:

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/data_mart.py in setup(self, db_credentials, schema, internal_db)
    153 
--> 154         payload = self._prepare_db_credentials_payload(db_credentials, schema, internal_db)
    155 

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/data_mart.py in _prepare_db_credentials_payload(self, db_credentials, schema, internal_db)
     58                     else:
---> 59                         raise ClientError("Unsupported type of db.")
     60             else:

ClientError: Unsupported type of db.

During handling of the above exception, another exception occurred:

ClientError                               Traceback (most recent call last)
<ipython-input-28-31615d0e23f2> in <module>()
     23         except:
     24             print('Setup failed, trying Db2 setup')
---> 25             ai_client.data_mart.setup(db_credentials=DB_CREDENTIALS, schema=DB_CREDENTIALS['username'])

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/data_mart.py in setup(self, db_credentials, schema, internal_db)
    152         """
    153 
--> 154         payload = self._prepare_db_credentials_payload(db_credentials, schema, internal_db)
    155 
    156         response = requests_session.put(

~/.local/lib/python3.5/site-packages/ibm_ai_openscale/data_mart.py in _prepare_db_credentials_payload(self, db_credentials, schema, internal_db)
     57                         db_type = "db2"
     58                     else:
---> 59                         raise ClientError("Unsupported type of db.")
     60             else:
     61                 if type(db_credentials) == DB2:

ClientError: Unsupported type of db.

**Comment by scottdangelo** [comment]
@kpullela Please try the latest notebook. I have updated the notebook and README instructions.

**Comment by scottdangelo** [comment]
Notebook has been reported as working. Closing this issue.

**Comment by olladapunaresh** [comment]
@scottdangelo Can u please give us the updated notebook link,Thanks
