### ISSUE TITLE
Having issues with WML service credentials

### ISSUE THREAD

**Issue by tranfm** [IBM/monitor-wml-model-with-watson-openscale#50]
Hi, I tried to run the jupyter notebook, everything was fine until I reached the section: Bind machine learning engines. I got the below error: 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-43-cb6594ee9a5e> in <module>
----> 1 binding_uid = ai_client.data_mart.bindings.add('WML instance', WatsonMachineLearningInstance(WML_CREDENTIALS))
      2 if binding_uid is None:
      3     binding_uid = ai_client.data_mart.bindings.get_details()['service_bindings'][0]['metadata']['guid']
      4 bindings_details = ai_client.data_mart.bindings.get_details()
      5 ai_client.data_mart.bindings.list()

/opt/conda/envs/Python36/lib/python3.6/site-packages/ibm_ai_openscale/engines/watson_machine_learning/instance.py in __init__(self, service_credentials)
     31 
     32         validate_type(service_credentials['apikey'], 'service_credentials.apikey', str, True)
---> 33         validate_type(service_credentials['username'], 'service_credentials.username', str, True)
     34         validate_type(service_credentials['password'], 'service_credentials.password', str, True)
     35         AIInstance.__init__(self, service_credentials['instance_id'], service_credentials, WMLConsts.SERVICE_TYPE)

KeyError: 'username'

Note that my machine learning instance uses IAM token (API key) so it does not contain username and password.  Moreover the section Save and deploy the model using the same credentials worked just fine. 

from watson_machine_learning_client import WatsonMachineLearningAPIClient
import json

wml_client = WatsonMachineLearningAPIClient(WML_CREDENTIALS)
......

published_model_details = wml_client.repository.store_model(model=model, meta_props=model_props, training_data=train_data, pipeline=pipeline)
 
By the way I ran the notebook in Watson Studio, Python 3.6, ibm-open-ai and pyspark are the same in the notebook. Could you please take a look? Thank you,

**Comment by scottdangelo** [comment]
Thanks for filing this issue. The older version of ibm-ai-openscale pinned in the notebook (2.1.7) di not support the apikey for WML, and required username and password.
I am upgrading the notebook to use ibm-ai-openscale v 2.1.14 for this reason.

**Comment by tranfm** [comment]
it works now. Thanks :-)
