### ISSUE TITLE
No longer works due to changes of IBM Cloud

### ISSUE THREAD

**Issue by lee-zhg** [IBM/monitor-wml-model-with-watson-openscale#53]
when running code in note book:

time.sleep(10)
subscription.quality_monitoring.enable(threshold=0.7, min_records=50)

Received errors:

MissingValue: No “output_data_schema” provided.
Reason: Column predictedLabel cannot be found in output_data_schema. Check if this column name is valid. Make sure that payload has been logged to populate schema.

**Comment by scottdangelo** [comment]
Hi. Can you please give some details regarding the failure? What failed? What to the errors look like?

**Comment by lee-zhg** [comment]
Below is the section in note book errors out:

Quality and feedback monitoring
Enable quality monitoring

Wait ten seconds to allow the payload logging table to be set up before we begin enabling monitors.

time.sleep(10)
subscription.quality_monitoring.enable(threshold=0.7, min_records=50)

Below are error messages:

---------------------------------------------------------------------------
MissingValue                              Traceback (most recent call last)
<ipython-input-40-c743309f02cf> in <module>()
      1 time.sleep(10)
----> 2 subscription.quality_monitoring.enable(threshold=0.7, min_records=50)

/home/spark/shared/user-libs/python3.6/ibm_ai_openscale/base_classes/configuration/quality_monitoring.py in enable(self, threshold, min_records, **kwargs)
     46 
     47         asset_properties = self._subscription.get_details()['entity']['asset_properties']
---> 48         validate_asset_properties(asset_properties, ['problem_type', 'output_data_schema'])
     49 
     50         if threshold is None or min_records is None:

/home/spark/shared/user-libs/python3.6/ibm_ai_openscale/utils/utils.py in validate_asset_properties(asset_properties, properties_list)
    358                 if 'predicted_target_field' in keys and asset_properties['predicted_target_field'] not in str(output_data_schema):
    359                     raise MissingValue(prop,
--> 360                                        reason='Column `{}` cannot be found in output_data_schema. Check if this column name is valid. Make sure that payload has been logged to populate schema.'.format(asset_properties['predicted_target_field']))
    361                 elif 'prediction_field' in keys and asset_properties['prediction_field'] not in str(output_data_schema):
    362                     raise MissingValue(prop,

MissingValue: No "output_data_schema" provided.
Reason: Column `predictedLabel` cannot be found in output_data_schema. Check if this column name is valid. Make sure that payload has been logged to populate schema.
